### ISSUE TITLE
[REQUEST] Add minimum playtime option / unmonitor when finished (90%+)

### ISSUE THREAD

**Issue by moostmartijn** [Shraymonks/unmonitorr#1]
First, thank you for this script, I was looking for something like this. 

I would like to have an option to have a minimum playtime of a movie and/or series before it gets unmonitored. At this moment it unmonitors the movies instantly. 
So if I just play a movie for 10 seconds to check or for whatever reason and don't finish it, I don't want it to be unmonitored.

**Comment by Shraymonks** [comment]
Hey @moostmartijn, you can use the `media.scrobble` event for exactly this. It triggers when media is played past 90%.
