### ISSUE TITLE
Multiple Radarr insrances will unmonitorr all instances when just one user watches

### ISSUE THREAD

**Issue by mikkelzzz3** [Shraymonks/unmonitorr#6]
Hi there, 
I have two Radarr instances. One for me, and one for my dad. I have two unmonitorr containers set up for us both. And two plex webhook instances for each unmonitorr container.

However, when my dad watches something, plex then sends the webhook to both unmonitorr containers, which unmonitors the movie in both Radarr instances. When it should only unmonitorr it for my dad. 

Plex webhooks has no filtration functionality, so I guess this would be a feature request :D I would love to be able to set an additional requirement on an unmonitorr container. Something like: "ACCOUNT_ID: 1", so that it only unmonitors if the account_id is the required which is provided by the Plex webhook payload.

**Comment by Shraymonks** [comment]
Hey @mikkelzzz3!

Just pushed 3d9938d78702a04e0448e5d12c5e93827ad604f7 to support this and it's available on docker hub if you re-pull latest.
There's a new `PLEX_ACCOUNTS` variable that you can use to filter on Plex account id or username. Should account for your use case!

**Comment by Shraymonks** [comment]
Can you double check that the admin username being used is correct? If you trigger an event and look in the plex logs (filter with "Webhook") you should see the exact username that triggers the event.

**Comment by mikkelzzz3** [comment]
Oh sorry, I didn't formulate myself properly. 

I meant, before this update when I watched something from the Plex Home admin account it would unmonitor, which was bothersome because I was just testing stuff. 

Now after the update, because I on purpose have not put the username of the admin account, this no longer happens :D

**Comment by Shraymonks** [comment]
Glad it all works now 😄

The Plex logs are useful but they were actually misleading when I was testing out this feature haha. It logs the admin account ID as `1` even though the account ID used for the webhook is the real account ID.
